name: Beta

on:
  workflow_dispatch:
  push:
    branches:
      - "**" # All branches
      - "!main" # Except main
      - "!master" # Except master
      - "!gh-pages" # Except gh-pages
      - "!develop" # Except develop
    tags:
      - "v*-beta.*"
    paths-ignore:
      - "README.md"
      - "example/**"

jobs:
  docker-release:
    name: Docker Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Container Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/overseerr-exporter
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,value=beta,enable=true
            type=ref,event=branch
            type=semver,pattern={{version}}-beta
            type=semver,pattern={{major}}.{{minor}}-beta
            type=semver,pattern={{major}}-beta
      - name: Build and Push Container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v6,linux/arm/v7
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            EXPORTER_VERSION=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.version'] }}
            REPOSITORY_OWNER=${{ github.repository_owner }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
